wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710009399.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.16.4
      6: 4.37.2
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
